# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff2fc64dd13157be41a2c9197df3a3f2d1f3e574a4ad59f5c8fb93663fd5383366854d1208bf402d35165e57faded03a010817794c13efd590c4330da0fc26d

test:
  secret_key_base: c25650788d05dce143083b41da4fe857b1b5992ce0e641bdfa99363bc9d97aafea1c266b9280b5e72bc2234e15dd158505f21d65d711189852730f8aff40d45d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
